[project]
name = "pdfreader"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "fitz>=0.0.1.dev2",
    "langchain-openai>=0.3.28",
    "notebook>=7.4.5",
    "pdfplumber>=0.11.7",
    "pypdf2>=3.0.1",
]
